export const tempTransactionDB = [
  {
    Type: "-",
    Value: 500,
    Date: new Date(2024, 0, 1).toISOString(),
    Comment: "test",
    Category: "Main expenses",
    owner: "test",
  },
  {
    Type: "-",
    Value: 258,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Products",
    owner: "test",
  },
  {
    Type: "-",
    Value: 258,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Car",
    owner: "test",
  },
  {
    Type: "-",
    Value: 100,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Self care",
    owner: "test",
  },
  {
    Type: "+",
    Value: 500,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Child care",
    owner: "test",
  },
  {
    Type: "+",
    Value: 200,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Child care",
    owner: "test",
  },
  {
    Type: "+",
    Value: 285,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Household products",
    owner: "test",
  },
  {
    Type: "-",
    Value: 500,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Education",
    owner: "test",
  },
  {
    Type: "-",
    Value: 100,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Leisure",
    owner: "test",
  },
  {
    Type: "+",
    Value: 450,
    Date: new Date().toISOString(),
    Comment: "test",
    Category: "Other expanses",
    owner: "test",
  },
  {
    Type: "-",
    Value: 500,
    Date: new Date(2024, 0, 1).toISOString(),
    Comment: "test",
    Category: "Main expenses",
    owner: "test",
  },
];
