export const tempTransactionDB = [
  {
    Date: new Date('2023-05-21').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'test',
    Sum: 500,
    Owner: 'test',
  },
  {
    Date: new Date('2023-05-12').toLocaleDateString(),
    Type: '-',
    Category: 'Car',
    Comment: 'Oil',
    Sum: 200,
    Owner: 'test',
  },
  {
    Date: new Date('2023-03-02').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'test',
    Sum: 1500,
    Owner: 'test',
  },
  {
    Date: new Date('2023-04-22').toLocaleDateString(),
    Type: '-',
    Category: 'Car',
    Comment: 'test',
    Sum: 420,
    Owner: 'test',
  },
  {
    Date: new Date('2023-01-11').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'test',
    Sum: 110,
    Owner: 'test',
  },
  {
    Date: new Date('2023-05-21').toLocaleDateString(),
    Type: '-',
    Category: 'Main expenses',
    Comment: 'test',
    Sum: 2500,
    Owner: 'test',
  },
  {
    Date: new Date('2023-05-24').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'test',
    Sum: 210,
    Owner: 'test',
  },
  {
    Date: new Date('2023-02-21').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'Wage',
    Sum: 3500,
    Owner: 'test',
  },
  {
    Date: new Date('2023-05-01').toLocaleDateString(),
    Type: '-',
    Category: 'Main expenses',
    Comment: 'test',
    Sum: 2320,
    Owner: 'test',
  },
  {
    Date: new Date('2023-05-11').toLocaleDateString(),
    Type: '-',
    Category: 'Main expenses',
    Comment: 'test',
    Sum: 278,
    Owner: 'test',
  },
  {
    Date: new Date('2023-02-28').toLocaleDateString(),
    Type: '+',
    Category: 'Income',
    Comment: 'Gift',
    Sum: 930,
    Owner: 'test',
  },
];
